### ISSUE TITLE
Cache refreshment

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/magento2-module-retailer#1]
The add-to-cart button does not appear on product page after choosing retailer and pickup date.

Steps to reproduce : 
- Enable FPC in system / cache configuration
- In frontend go on a product page
- Choose a valid pickup store and pickup date and validate

We are working with varnish, is there some headers to add to the varnish conf ?

**Comment by romainruaud** [comment]
There is two main points to check if you are using Varnish : 
- You should detect the cookies in the VCL and condition the cache variance to their presence.

This can be something like this (untested) : 

into the **vcl_recv** function : 

<pre>
    if (req.http.Cookie && req.http.Cookie ~ "(?i)retailer_id=") {
        set req.http.X-Retailer-Id = regsub(req.http.Cookie, "(?i).*retailer_id=([^;]+).*", "\1");
        # Ignore it if empty
        if (req.http.X-Retailer-Id ~ "^ *$") { unset req.http.X-Retailer-Id; }
    }
    if (req.http.Cookie && req.http.Cookie ~ "(?i)pickup_date=") {
        set req.http.X-Pickup-Date = regsub(req.http.Cookie, "(?i).*pickup_date=([^;]+).*", "\1");
        # Ignore it if empty
        if (req.http.X-Pickup-Date ~ "^ *$") { unset req.http.X-Pickup-Date; }
    }
</pre>

And on the **vcl_hash** function : 

<pre>
    if (req.http.X-Retailer-Id) {
        hash_data(req.http.X-Retailer-Id);
    }
    if (req.http.X-Retailer-Id) {
        hash_data(req.http.X-Retailer-Id);
    }
</pre>
- Varnish should also not remove the retailer cookie on request. Or you have to retrieve them on PHP Side from the Headers (X-Retailer-Id and X-Pickup-Date) to flag the user session properly.

**Comment by AymericJoubert** [comment]
Here are the headers i added : 

In vcl_recv : 

```
if (req.http.Cookie && req.http.Cookie ~ "smile_retailer_id=") {
    set req.http.X-Retailer-Id = regsub(req.http.Cookie, ".*smile_retailer_id=([^;]+).*", "\1");
    # Ignore it if empty
    if (req.http.X-Retailer-Id ~ "^ *$") { unset req.http.X-Retailer-Id; }
}

if (req.http.Cookie && req.http.Cookie ~ "smile_retailer_pickupdate=") {
    set req.http.X-Pickup-Date = regsub(req.http.Cookie, ".*smile_retailer_pickupdate=([^;]+).*", "\1");
    # Ignore it if empty
    if (req.http.X-Pickup-Date ~ "^ *$") { unset req.http.X-Pickup-Date; }
}
```

In vcl_hash : 

```
if (req.http.X-Retailer-Id) {
    hash_data(req.http.X-Retailer-Id);
}

if (req.http.X-Pickup-Date) {
    hash_data(req.http.X-Pickup-Date);
}
```

This works, we now have a cache by retailer and pickup date.
Thanks
