### ISSUE TITLE
Use Default Value of URL key field not taken into account

### ISSUE THREAD

**Issue by Maikel-Koek** [Smile-SA/magento2-module-retailer#12]
The 'Use Default Value' checkbox of the 'URL key' field is emptied when saving the entity at a store view level, and the field remains empty, although there is a value at the global level.

I'm not using the entire suite, I just installed `smile/module-store-locator`, I'm checked out at:

https://github.com/Smile-SA/magento2-module-retailer/commit/5f093c8715ac90bec4452f5afd67b09b24483d85
https://github.com/Smile-SA/magento2-module-seller/commit/0bb47c998acdf6b26f1eaaf567fea40450fe3546

**Comment by Maikel-Koek** [comment]
This also seems to happen occasionally with all the 'Contact' tab fields.

**Comment by delyriand** [comment]
Hi @Maikel-Koek 

Thank you for report this issue.
Indeed, when we specify a url key at a store view, save this retailer and after we want to use the default value, the field is empty.

But, I was not able to reproduce the issue with the 'Contact' tab attributes.

Best regards

**Comment by delyriand** [comment]
Hello @Chacalbis,

if you can modify your code instead of an observer, i prefer this solution.

I closed the PR but do not hesitate to contribute again ;)

**Comment by delyriand** [comment]
Hello @Maikel-Koek,

I will correct the problem with the url_key field but for  the 'Contact' tab attributes, it is a [magento bug](https://github.com/magento/magento2/issues/13665). When you save Offer (or Category) for a specific store view and you don't deploy other tabs - like Contact - the "Use Default Value" is removed.
