### ISSUE TITLE
1.2.6 Fatal error

### ISSUE THREAD

**Issue by MarianMates** [Smile-SA/magento2-module-retailer#17]
Hello, upgrade 1.2.5 => 1.2.6 breaks Magento 2.2.3 and 2.2.5 on compilation time.
Fatal error: Interface 'Magento\Framework\App\Action\HttpPostActionInterface' not found in /var/www/html/vendor/smile/module-retailer/Controller/Adminhtml/Retailer/MassEnable.php on line 29

**Comment by loiczam** [comment]
Hi @MarianMates ,

this interface is implemented in Magento 2.3. 
For the moment, the version 1.2.6 is functional only with Magento 2.3.

**Comment by Fdec** [comment]
Hi @MarianMates 

I'm working on the fix, I will release it very soon

**Comment by Fdec** [comment]
See the next release https://github.com/Smile-SA/magento2-module-retailer/releases/tag/1.2.7
