### ISSUE TITLE
Retailer adding issue..

### ISSUE THREAD

**Issue by shravan148** [Smile-SA/magento2-module-retailer#20]
when we open the retailers from seller menu in the dash... its showing this error and there is no schema file in setup folder of retailer module....SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dump.smile_retailer_address' doesn't exist, query was: SELECT COUNT(*) FROM `smile_seller_entity` AS `e` LEFT JOIN `smile_retailer_address` AS `extension_attribute_address` ON e.entity_id = extension_attribute_address.retailer_id WHERE (`e`.`attribute_set_id` = '14'

**Comment by Fdec** [comment]
Hi @shravan148 

What is your version of the module ? And version of your Magento ?
Have you made a specific source code ?  Because your error talk about table "dump.smile_retailer_address", and it's not a table of the module.
