### ISSUE TITLE
Problem in the Version 1.2.8.1

### ISSUE THREAD

**Issue by theTruth777** [Smile-SA/magento2-module-retailer#23]
Hi there

looks like you have released a new module-retailer version "1.2.8.1" without updating the corresponding "module-seller".
We are receiving the following error: 

> Uncaught Error: Undefined class constant 'MEDIA_PATH' in /var/www/html/vendor/smile/module-retailer/Controller/Adminhtml/Retailer/Save.php on line 75

We also checked your github. the master branch seems to be working but the stable Tag 1.2.5 is too old.
Please fix this as this just broke our dev-system and we can deploy the production anymore

we are using the following modules:

        "smile/elasticsuite": "2.6.9",
        "smile/elasticsuite-for-retailer": "1.4.4"

**Comment by romainruaud** [comment]
Hi,

don't use 1.2.8.1 and rollback to previous version.
