### ISSUE TITLE
Error when delete All retailer

### ISSUE THREAD

**Issue by hiepnt93** [Smile-SA/magento2-module-retailer#24]
i got this issue when delete all retailer (Choose Select All instead of Select Visible)

Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/smile/module-retailer/Controller/Adminhtml/Retailer/MassDelete.php on line 39

**Comment by Fdec** [comment]
hi @hiepnt93 

Can you give me some details ? 


Magento Version :


Module Store Retailer Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

I try on my magento 2.3.1 and it's works
