### ISSUE TITLE
Category Listing

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/magento2-module-retailer#3]
When retailer and pickup date are selected, all the available products are shown on all categories pages, not depending off the selected categories in product configuration.

**Comment by romainruaud** [comment]
We are not able to reproduct this issue on our testing environment. Are you sure it happens on a raw Magento with the retailer suite freshly installed ? 

Are you speaking about a normal category or a virtual one ? Could you check the ES query is OK ? (you can see the query in debug.log after enabling debug mode of elasticsuite).
